### PR TITLE
removing other ukrainian-controlled cities

### PR DESCRIPTION
**Pull request by denysdovhan**
I doubt anyone from russian communities would be welcome in Ukraine in the foreseeable future. Moreover, at the moment, this light might look like blurring the boundaries between two countries.

People from git blame to be notified @sudodoki @roman01la @tyv 

P.S: Looking forward when Simferopol will be removed from here as well.

### CODE REVIEW

**Comment by denysdovhan** [comment]
I guess notified people are going to approve this change.

**Comment by pepelsbey** [comment]
I’d wait for meetup owners to send their own PRs or support this one before making any changes.

**Comment by denysdovhan** [comment]
@pepelsbey this isn’t completely reasonable, because some of these entries were added by you and other members of WS-community in a first place. Original owners might not even know. Communities from Odesa or Poltava, for example.

**Comment by pepelsbey** [comment]
@denysdovhan still, I’m not planning to remove links only because you think they shouldn’t be here.

**Comment by roman01la** [comment]
ChernihivJS is dead, I have no objections to remove the entry from the listing.

**Comment by pepelsbey** [comment]
I’d prefer to update the list, not remove links. I hope you understand the difference.

If meetup is not active or it’s not Russian-speaking anymore, for example.

**Review by m1n0s — APPROVED** [review]

**Review by alexeyraspopov — APPROVED** [review]

**Comment by sudodoki** [comment]
I'm okay with removing `kyivjs`, thanks for saving a trip to edit-PR cycle, @denysdovhan

**Comment by denysdovhan** [comment]
@blackrabbit99 (KharkivJS organizer) has upvoted the PR, just in case you didn't notice. cc @pepelsbey

**Review by sudodoki — APPROVED** [review]

**Comment by blackrabbit99** [comment]
I would agree with @denysdovhan. @pepelsbey Could you pls remove KharkivJS and PoltavaJS from this list. Ukrainian community leaders support this PR.

**Review by blackrabbit99 — APPROVED** [review]

**Comment by tyv** [comment]
👍🏻for removing KyivJS

**Comment by matochu** [comment]
Yep. It is better to remove all Ukrainian cities (BeerJS Kyiv too)

**Review by denysovkos — APPROVED** [review]

**Comment by pepelsbey** [comment]
Thank you for bringing attention to this outdated repository. Instead of removing meetups one by one, I decided to archive this repository. On one hand, it will preserve history, and on the other, it will clearly show its status.

Offtopic: it was nice talking to you, I hope not the last time. Слава Україні 💙💛

**Pull request closed without merging**
